[package]

name = "zhelezo"
version = "0.7.0-beta.1"
description = "Extensible, Concurrency Focused Web Development in Rust."
readme = "README.md"
repository = "https://github.com/sunng87/zhelezo"
documentation = "http://docs.rs/crates/zhelezo"
license = "MIT"
authors = [
    "Jonathan Reem <jonathan.reem@gmail.com>",
    "Zach Pomerantz <zmp@umich.edu>",
    "Michael Sproul <micsproul@gmail.com>",
    "Patrick Tran <patrick.tran06@gmail.com>"
]

[features]
default = []
ssl = ["native-tls", "tokio-tls"]

[dependencies]
typemap = "0.3"
url = "1.1"
plugin = "0.2"
mime_guess = "2.0.0-alpha.1"
modifier = "0.1"
log = "0.3"
hyper = "0.11"
futures = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-proto = "0.1"
futures-cpupool = "0.1"
tokio-tls = { version = "0.1.1", optional = true, features = ["tokio-proto"] }
native-tls = { version = "0.1.1", optional = true }

[dev-dependencies]
time = "0.1"
mime = "0.3"
